use phf::phf_map;

pub enum Cell {
    Zero32,
    Bool32,
    Skip32,
    EmptyStr,
    Str(i8),
}

pub const NXD_COLUMNS: phf::Map<&'static str, &[Cell]> = phf_map! {
    "ability" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::Skip32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        // NOTE: Some rows have multiple (but unrelated) elements
    ],
    "achievement" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
    ],
    "battleobjective" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Zero32,
        Cell::Bool32,
    ],
    "battlesignal" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(0),
        Cell::Bool32,
    ],
    "bgmmode" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Bool32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Skip32,
    ],
    "book" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "captionfreeword" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
    ],
    "chapter" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Str(0),
    ],
    "charaname" => &[
        Cell::Bool32,
        Cell::EmptyStr,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Bool32,
    ],
    "c_mes_id_sample" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::Bool32,
    ],
    "collection" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "deepdungeon" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
    ],
    "gossip" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        // NOTE: Some rows have multiple (but unrelated) elements
    ],
    "guide" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Skip32,
    ],
    "guidepage" => &[  // Type 2!
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "item" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Str(-3),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "job" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Str(-3),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "jobcommand" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "journal" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "land" => &[
        Cell::Zero32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
    ],
    "landscapeheight" => &[
        Cell::Zero32,
        Cell::Str(0),
    ],
    "launcherguide" => &[  // Type 2!
        Cell::Zero32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Skip32,
    ],
    "loreaffiliation" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Str(0),
    ],
    "loredictionary" => &[  // Type 2!
        Cell::Zero32,
        Cell::EmptyStr,

        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,

        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Str(-3),

        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,

        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,

        Cell::Skip32,
        Cell::Skip32,
    ],
    "loredictionarycategory" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Str(0),
    ],
    "lorenamealias" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
    ],
    "novel00" => &[
        Cell::Bool32,
        Cell::Str(0),
    ],
    "novel01" => &[
        Cell::Bool32,
        Cell::Str(0),
    ],
    "novel02" => &[
        Cell::Bool32,
        Cell::Str(0),
    ],
    "novel03" => &[
        Cell::Bool32,
        Cell::Str(0),
    ],
    "novel04" => &[
        Cell::Bool32,
        Cell::Str(0),
    ],
    "placename" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
    ],
    "poachitem" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Str(-3),
        Cell::Str(-4),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "profit" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Str(-3),
        Cell::Str(-4),
        Cell::Str(-5),
        Cell::Str(-6),
        Cell::Skip32,
        Cell::Skip32,
    ],
    "profitbonusitem" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
    ],
    "profitclientname" => &[
        Cell::Zero32,
        Cell::Str(0),
    ],
    "speaker" => &[
        Cell::Zero32,
        Cell::Str(0),
    ],
    "systembonusitem" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "systembonusspecialitem" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
    ],
    "telemetryachievement" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(-4),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(-11),
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
    ],
    "town" => &[
        Cell::Skip32,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(-4),
        Cell::Skip32,
        Cell::Str(-6),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,  // seems U8 + U16
    ],
    "ui" => &[
        Cell::Skip32,
        Cell::Str(0),
    ],
    "uichronicleperiod" => &[
        Cell::Zero32,
        Cell::Zero32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Bool32,
    ],
    "uiclassicsubtitles" => &[  // Type 2!
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Bool32,
    ],
    "uielementattribute" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Skip32,
    ],
    "uiitemcategory" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "uijobabilityhelp" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
    ],
    "uisituationsubtitles" => &[  // Type 2!
        Cell::Zero32,
        Cell::Str(0),
    ],
    "uistatuseffect" => &[
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,  // seems 2 x i16
    ],
    "uistatuseffectcategory" => &[
        Cell::Zero32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::Skip32,
    ],
    "uisubtitles" => &[  // Type 2!
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Zero32,
    ],
    "worldmapprogressinfo" => &[  // Type 2!
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Skip32,
    ],
    "zodiacstone" => &[  // Type 2!
        Cell::Zero32,
        Cell::EmptyStr,
        Cell::Skip32,
        Cell::Skip32,
        Cell::Str(0),
        Cell::Str(-1),
        Cell::Str(-2),
        Cell::Skip32,
        Cell::Skip32,
        Cell::Bool32,
    ],
};
